added datev.de
lieser/dkim_verifier pull request #209
Opened 2020-08-22 10:53 UTC by andreasschulze

on behalf of DATEV this PR add our Logo

2020-08-25 19:38 UTC, lieser requested changes
Thanks for the icon and rule.

There seems to be something wrong with the icon. If I try to view the icon in Firefox (https://raw.githubusercontent.com/lieser/dkim_verifier/8d48e0ede1eb4fbffd2bc127c6f8fd389ede4807/data/favicon/datev.de.ico) it only shows a Grey box. And it also didn't work inside the add-on in the quick test I did.

2020-08-29 08:36 UTC, andreasschulze commented
I wasnt's aware myself about the display issue but I can reproduce it. I informed our webmaster and wait for response.

2020-11-15 16:58 UTC, andreasschulze commented
updated our branch to contain an [favicon, that display more then a grey box](https://raw.githubusercontent.com/datev/dkim_verifier/master/data/favicon/datev.de.ico)

2020-11-15 21:35 UTC, lieser approved these changes

2020-11-15 21:36 UTC, merged